server:
  port: 8080
  context-path: /apns-server

spring:
  datasource:
    name: apnsdatasource
    url: jdbc:mysql://127.0.0.1:3306/apns
    username: root
    password: lotus

apple:
  tlsauth:
    p12filepath: E:\\workspace\\APNSServerDEMO\\src\\main\\resources\\apple\\apns-dev-key.p12
    p12filepwd: 123456
  tokenauth:
    p8filepath: classpath:apple/key.p8
    teamid: teamid
    keyid: keyid
  topic: cn.com.westone.westmail

mybatis:
  mapper-locations: classpath:mybatis/sqlmapper/*Mapper.xml
  type-aliases-package: com.ps.apns.dao.model