server:
  port: 8080
  context-path: /apns-server

spring:
  datasource:
    name: apnsdatasource
    url: jdbc:mysql://127.0.0.1:3306/apns
    username: root
    password: lotus

apple:
  tlsauth:
    p12filepath: E:\\workspace\\APNSServerDEMO\\src\\main\\resources\\apple\\apns-dev-cert.p12
    p12filepwd: 123456
  tokenauth:
    p8filepath: E:\\workspace\\APNSServerDEMO\\src\\main\\resources\\apple\\AuthKey_H47XK58T36.p8
    teamid: teamId
    keyid: keyId
  topic: cn.com.westone.westmail

mybatis:
  mapper-locations: classpath:mybatis/sqlmapper/*Mapper.xml
  type-aliases-package: com.ps.apns.dao.model